export const INITIAL_PACKAGES = [
  {
    name: '20 Mbps Home Starter',
    code: 'PKG-20M',
    speedDownMbps: 20,
    speedUpMbps: 20,
    contentionRatio: '1:4 Shared',
    pricePkrMonthly: '2450.00',
    ipPool: 'pool_residential_dhcp',
    activeSubscribers: 980,
    isPopular: false,
  },
  {
    name: '50 Mbps Ultra Fiber',
    code: 'PKG-50M',
    speedDownMbps: 50,
    speedUpMbps: 50,
    contentionRatio: '1:2 Low Contention',
    pricePkrMonthly: '3850.00',
    ipPool: 'pool_residential_dhcp',
    activeSubscribers: 1840,
    isPopular: true,
  },
  {
    name: '100 Mbps Pro Enterprise',
    code: 'PKG-100M',
    speedDownMbps: 100,
    speedUpMbps: 100,
    contentionRatio: '1:1 Dedicated Symmetrical',
    pricePkrMonthly: '7200.00',
    ipPool: 'pool_enterprise_static',
    activeSubscribers: 420,
    isPopular: false,
  },
  {
    name: '200 Mbps Dedicated Giga',
    code: 'PKG-200M',
    speedDownMbps: 200,
    speedUpMbps: 200,
    contentionRatio: '1:1 CIR Dedicated',
    pricePkrMonthly: '14500.00',
    ipPool: 'pool_enterprise_static',
    activeSubscribers: 110,
    isPopular: false,
  },
  {
    name: '15 Mbps Smart Saver',
    code: 'PKG-15M',
    speedDownMbps: 15,
    speedUpMbps: 15,
    contentionRatio: '1:8 Shared',
    pricePkrMonthly: '1850.00',
    ipPool: 'pool_residential_dhcp',
    activeSubscribers: 650,
    isPopular: false,
  },
];

export const INITIAL_DEPARTMENTS = [
  {
    name: 'Helpdesk & Customer Support (L1/L2)',
    code: 'DEPT-HLP',
    leadName: 'Khurram Shahzad',
    headcount: 12,
    activeTickets: 8,
    slaTargetHours: 2,
    color: 'blue',
  },
  {
    name: 'NOC & Core Optical Engineering',
    code: 'DEPT-NOC',
    leadName: 'Zubair Ahmed',
    headcount: 8,
    activeTickets: 5,
    slaTargetHours: 1,
    color: 'purple',
  },
  {
    name: 'Field Operations & Fiber Splicing Vans',
    code: 'DEPT-FLD',
    leadName: 'Usman Ali',
    headcount: 16,
    activeTickets: 14,
    slaTargetHours: 4,
    color: 'emerald',
  },
  {
    name: 'Billing, Accounts & Cash Recovery',
    code: 'DEPT-BIL',
    leadName: 'Fatima Noor',
    headcount: 6,
    activeTickets: 2,
    slaTargetHours: 6,
    color: 'amber',
  },
  {
    name: 'Corporate Sales & Onboarding Feasibility',
    code: 'DEPT-SLS',
    leadName: 'Bilal Qureshi',
    headcount: 5,
    activeTickets: 3,
    slaTargetHours: 8,
    color: 'rose',
  },
];

export const INITIAL_LEADS = [
  {
    leadNo: 'LD-9921',
    applicantName: 'Dr. Bilal Qureshi',
    fatherName: 'Muhammad Qureshi',
    phone: '+92 300 4455667',
    cnic: '37405-9921445-7',
    address: 'House 58, Street 4, Sector F-10/3, Islamabad',
    branchName: 'Islamabad Core (F-10 HQ)',
    selectedPackage: '50 Mbps Ultra Fiber',
    connectionType: 'GPON Fiber',
    deviceModel: 'Huawei HG8245H',
    macAddress: '48:8A:D2:99:A1:01',
    fiberDistanceMeters: 140,
    stage: 'feasibility_passed',
    status: 'Pending',
    fatBoxNearest: 'FAT-10/2-04',
    portAvailable: true,
    otcPkr: '5000.00',
    monthlyBillPkr: '3850.00',
    otcPaidPkr: '5000.00',
    monthlyBillPaidPkr: '0.00',
    assignedVan: 'VAN-03 (Usman)',
    assignedBy: 'Khurram Shahzad',
    remarks: 'Feasibility passed. 12 Core spare in FAT-04.',
    opticalSignalDbm: '-18.4',
  },
  {
    leadNo: 'LD-9922',
    applicantName: 'Sarah Jenkins (USA Embassy Res)',
    fatherName: 'Robert Jenkins',
    phone: '+92 333 7891234',
    cnic: 'Diplomatic-US-8821',
    address: 'Bungalow 12, Diplomatic Enclave, G-5, Islamabad',
    branchName: 'Islamabad Core (F-10 HQ)',
    selectedPackage: '100 Mbps Pro Enterprise',
    connectionType: 'Active Ethernet (1:1)',
    deviceModel: 'Mikrotik RB4011 + SFP',
    macAddress: 'B8:69:F4:11:55:C3',
    fiberDistanceMeters: 450,
    stage: 'installation_scheduled',
    status: 'Active',
    fatBoxNearest: 'FAT-DIP-01',
    portAvailable: true,
    otcPkr: '15000.00',
    monthlyBillPkr: '7200.00',
    otcPaidPkr: '15000.00',
    monthlyBillPaidPkr: '7200.00',
    assignedVan: 'VAN-01 (Rashid)',
    assignedBy: 'Tariq Mehmood',
    remarks: 'High priority corporate SLA required.',
    opticalSignalDbm: '-16.1',
  },
  {
    leadNo: 'LD-9923',
    applicantName: 'Malik Jahangir Khan',
    fatherName: 'Malik Sikandar',
    phone: '+92 321 5566778',
    cnic: '37405-1122334-9',
    address: 'Plaza 4, Main Double Road, Sector E-11/2, Islamabad',
    branchName: 'Rawalpindi Satellite',
    selectedPackage: '50 Mbps Ultra Fiber',
    connectionType: 'GPON Fiber',
    deviceModel: 'ZTE F660',
    fiberDistanceMeters: 380,
    stage: 'inquiry',
    status: 'Pending',
    fatBoxNearest: 'FAT-E11-12',
    portAvailable: false,
    otcPkr: '5000.00',
    monthlyBillPkr: '3850.00',
    otcPaidPkr: '0.00',
    monthlyBillPaidPkr: '0.00',
    assignedVan: 'VAN-02 (Farhan)',
    assignedBy: 'Online Portal',
    remarks: 'FAT box ports full. Requires 1:8 splitter addition on pole 14.',
  },
  {
    leadNo: 'LD-9924',
    applicantName: 'Taimoor Shah Software House',
    fatherName: 'Shahbaz Khan',
    phone: '+92 345 9988776',
    cnic: '37405-6677889-1',
    address: 'Floor 3, Executive Heights, Sector F-11 Markaz, Islamabad',
    branchName: 'Islamabad Core (F-10 HQ)',
    selectedPackage: '200 Mbps Dedicated Giga',
    connectionType: 'Fiber Direct Drop',
    deviceModel: 'Cisco 2960 + SFP Media Conv',
    fiberDistanceMeters: 210,
    stage: 'activated',
    status: 'Active',
    fatBoxNearest: 'FAT-F11-CORE-02',
    portAvailable: true,
    otcPkr: '25000.00',
    monthlyBillPkr: '14500.00',
    otcPaidPkr: '25000.00',
    monthlyBillPaidPkr: '14500.00',
    assignedVan: 'VAN-01 (Rashid)',
    assignedBy: 'Tariq Mehmood',
    remarks: 'Live on GPON 0/1/6. Latency tested to Cloudflare 1.1.1.1: 4ms.',
    opticalSignalDbm: '-15.8',
  },
];

export const INITIAL_SHIFTS = [
  {
    shiftName: 'Morning Operational (Roster A)',
    timeRange: '08:00 - 16:00 PKT',
    department: 'Helpdesk & Customer Support (L1/L2)',
    assignedStaff: ['Khurram Shahzad', 'Hamza Abbasi', 'Ayesha Malik'],
    onCallStandby: ['Zeeshan Haider'],
    branchName: 'Islamabad Core (F-10 HQ)',
  },
  {
    shiftName: 'Evening Peak Triage (Roster B)',
    timeRange: '16:00 - 00:00 PKT',
    department: 'Helpdesk & Customer Support (L1/L2)',
    assignedStaff: ['Fatima Noor', 'Noman Raza', 'Bilal Tariq'],
    onCallStandby: ['Hamza Abbasi'],
    branchName: 'Islamabad Core (F-10 HQ)',
  },
  {
    shiftName: 'Night Core Watch (Roster C)',
    timeRange: '00:00 - 08:00 PKT',
    department: 'NOC & Core Optical Engineering',
    assignedStaff: ['Zubair Ahmed', 'Danyal Siddiqui'],
    onCallStandby: ['Khurram Shahzad'],
    branchName: 'Islamabad Core (F-10 HQ)',
  },
  {
    shiftName: 'On-Call Emergency Fiber Splicers',
    timeRange: '24 / 7 Standby Emergency',
    department: 'Field Operations & Fiber Splicing Vans',
    assignedStaff: ['Usman Ali', 'Kamran Khan', 'Rashid Mehmood'],
    onCallStandby: ['Farhan Akhtar'],
    branchName: 'Islamabad Core (F-10 HQ)',
  },
];

export const INITIAL_ATTENDANCE = [
  {
    staffId: 'usr-01',
    staffName: 'Khurram Shahzad',
    department: 'Helpdesk & Customer Support (L1/L2)',
    date: '2026-09-06',
    clockIn: new Date(Date.now() - 6 * 3600 * 1000),
    clockOut: null,
    checkInMethod: 'biometric',
    isLate: false,
    overtimeHours: '0.00',
    overtimeRateMultiplier: '1.50',
    status: 'present',
  },
  {
    staffId: 'usr-02',
    staffName: 'Zubair Ahmed',
    department: 'NOC & Core Optical Engineering',
    date: '2026-09-06',
    clockIn: new Date(Date.now() - 7 * 3600 * 1000),
    clockOut: null,
    checkInMethod: 'biometric',
    isLate: false,
    overtimeHours: '1.50',
    overtimeRateMultiplier: '1.50',
    status: 'present',
  },
  {
    staffId: 'usr-03',
    staffName: 'Usman Ali',
    department: 'Field Operations & Fiber Splicing Vans',
    date: '2026-09-06',
    clockIn: new Date(Date.now() - 5 * 3600 * 1000),
    clockOut: null,
    checkInMethod: 'geofenced_mobile',
    isLate: true,
    overtimeHours: '2.00',
    overtimeRateMultiplier: '1.50',
    status: 'present',
  },
  {
    staffId: 'usr-04',
    staffName: 'Fatima Noor',
    department: 'Billing, Accounts & Cash Recovery',
    date: '2026-09-06',
    clockIn: new Date(Date.now() - 6 * 3600 * 1000),
    clockOut: null,
    checkInMethod: 'biometric',
    isLate: false,
    overtimeHours: '0.00',
    overtimeRateMultiplier: '1.50',
    status: 'present',
  },
];

export const INITIAL_WORK_ORDERS = [
  {
    taskNo: 'WO-8842',
    title: 'Drop Cable OTDR Splice Repair',
    type: 'OTDR Splicing Repair',
    subscriberCode: 'CUS-84920',
    subscriberName: 'Ali Hassan',
    address: 'House 24, Street 12, Sector F-10/2, Islamabad',
    priority: 'Critical',
    assignedTo: 'Usman Ali (Field Tech)',
    vanNo: 'VAN-03 (Field)',
    status: 'in_progress',
    dueAt: new Date(Date.now() + 2 * 3600 * 1000),
  },
  {
    taskNo: 'WO-8843',
    title: 'New Optical ONU Installation',
    type: 'Fiber Drop Installation',
    subscriberCode: 'CUS-84922',
    subscriberName: 'Zeeshan Qadir',
    address: 'Flat 4B, Silver Heights, Sector E-11/2, Islamabad',
    priority: 'High',
    assignedTo: 'Kamran Khan',
    vanNo: 'VAN-01 (Install)',
    status: 'en_route',
    dueAt: new Date(Date.now() + 4 * 3600 * 1000),
  },
  {
    taskNo: 'WO-8844',
    title: 'Dual-Band Wi-Fi 6 Router Upgrade',
    type: 'Router Replacement',
    subscriberCode: 'CUS-84923',
    subscriberName: 'Hamza Farooq',
    address: 'House 18, St 2, Sector F-8/4, Islamabad',
    priority: 'Normal',
    assignedTo: 'Rashid Mehmood',
    vanNo: 'VAN-02 (Hardware)',
    status: 'assigned',
    dueAt: new Date(Date.now() + 6 * 3600 * 1000),
  },
  {
    taskNo: 'WO-8845',
    title: 'Doorstep Cash Recovery (Overdue 2 Months)',
    type: 'Doorstep Cash Recovery',
    subscriberCode: 'CUS-84924',
    subscriberName: 'Kashif Rasheed',
    address: 'House 77, St 19, Sector G-9/3, Islamabad',
    priority: 'Normal',
    assignedTo: 'Fatima Noor (Recovery)',
    vanNo: 'BIKE-02 (Recovery)',
    status: 'todo',
    dueAt: new Date(Date.now() + 8 * 3600 * 1000),
  },
];

export const INITIAL_SLA_RULES = [
  {
    priority: 'Critical',
    targetFirstResponseMins: 15,
    targetResolutionHours: 2,
    autoEscalateAfterMins: 30,
    escalateToRole: 'NOC Lead / Operations Director',
    notifyChannels: ['SMS Gateway', 'Telegram Bot', 'Dashboard Alarm Audio'],
  },
  {
    priority: 'High',
    targetFirstResponseMins: 30,
    targetResolutionHours: 4,
    autoEscalateAfterMins: 60,
    escalateToRole: 'Support Supervisor',
    notifyChannels: ['SMS Gateway', 'Email Alert'],
  },
  {
    priority: 'Normal',
    targetFirstResponseMins: 60,
    targetResolutionHours: 12,
    autoEscalateAfterMins: 180,
    escalateToRole: 'Department Lead',
    notifyChannels: ['Dashboard Notification'],
  },
  {
    priority: 'Low',
    targetFirstResponseMins: 120,
    targetResolutionHours: 24,
    autoEscalateAfterMins: 360,
    escalateToRole: 'Helpdesk Queue',
    notifyChannels: ['Email Digest'],
  },
];
