import { Conversation, Message } from '@/types/chat.types';
import { Customer360 } from '@/types/customer.types';

export const mockDeskConversations: Conversation[] = [
  {
    id: 'conv_ali_f10_01',
    companyId: 'cmp_prime_networks_01',
    customerId: 'cus_ali_f10',
    initiatedBy: 'customer',
    status: 'active',
    priority: 'high',
    subject: 'LOS Red light blinking on GPON router',
    unreadCountCustomer: 0,
    unreadCountStaff: 2,
    createdAt: '2026-08-25T10:40:00Z',
    updatedAt: '2026-08-25T10:42:00Z',
    lastMessageAt: '2026-08-25T10:42:00Z',
    customer: {
      id: 'cus_ali_f10',
      companyId: 'cmp_prime_networks_01',
      customerCode: 'CUS-F10-9102',
      fullName: 'Ali Hassan',
      phone: '+92 300 5551234',
      username: 'ali_f10',
      address: 'House 142, Street 18, Sector F-10/2',
      area: 'Sector F-10/2',
      city: 'Islamabad',
      customerClass: 'residential',
      packageName: '50 Mbps Ultra Fiber',
      packageSpeed: '50 Mbps',
      monthlyBilling: 3500,
      pppoeStatus: 'online',
      onuSignalDbm: -19.24,
      oltPonPort: 'Huawei-MA5608T // PON-4',
      status: 'active',
      languagePreference: 'en',
      createdAt: '2026-01-10T00:00:00Z',
      updatedAt: '2026-08-25T00:00:00Z',
    },
    lastMessage: {
      id: 'msg_03',
      conversationId: 'conv_ali_f10_01',
      companyId: 'cmp_prime_networks_01',
      senderType: 'staff',
      senderName: 'NOC Lead (Moiz)',
      messageType: 'text',
      content: 'Optical fault confirmed on PON-4. Field Engineer Imran dispatched.',
      status: 'delivered',
      isInternalNote: false,
      isPublicNote: false,
      isDeleted: false,
      createdAt: '2026-08-25T10:42:00Z',
    },
  },
  {
    id: 'conv_fatima_g11_02',
    companyId: 'cmp_prime_networks_01',
    customerId: 'cus_fatima_g11',
    initiatedBy: 'customer',
    status: 'waiting',
    priority: 'normal',
    subject: 'Monthly invoice payment confirmation proof',
    unreadCountCustomer: 0,
    unreadCountStaff: 1,
    createdAt: '2026-08-25T10:30:00Z',
    updatedAt: '2026-08-25T10:35:00Z',
    lastMessageAt: '2026-08-25T10:35:00Z',
    customer: {
      id: 'cus_fatima_g11',
      companyId: 'cmp_prime_networks_01',
      customerCode: 'CUS-G11-4011',
      fullName: 'Fatima Khan',
      phone: '+92 321 9876543',
      username: 'fatima_g11',
      address: 'House 88, Street 4, Sector G-11/3',
      area: 'Sector G-11/3',
      city: 'Islamabad',
      customerClass: 'residential',
      packageName: '100 Mbps Boost',
      packageSpeed: '100 Mbps',
      monthlyBilling: 5500,
      pppoeStatus: 'online',
      onuSignalDbm: -18.8,
      oltPonPort: 'Huawei-MA5608T // PON-2',
      status: 'active',
      languagePreference: 'en',
      createdAt: '2026-02-15T00:00:00Z',
      updatedAt: '2026-08-25T00:00:00Z',
    },
    lastMessage: {
      id: 'msg_04',
      conversationId: 'conv_fatima_g11_02',
      companyId: 'cmp_prime_networks_01',
      senderType: 'customer',
      senderName: 'Fatima Khan',
      messageType: 'text',
      content: 'I have uploaded Nayapay transfer receipt for Rs. 5,500.',
      status: 'delivered',
      isInternalNote: false,
      isPublicNote: false,
      isDeleted: false,
      createdAt: '2026-08-25T10:35:00Z',
    },
  },
  {
    id: 'conv_zahid_blue_03',
    companyId: 'cmp_prime_networks_01',
    customerId: 'cus_zahid_blue',
    initiatedBy: 'customer',
    status: 'closed',
    priority: 'urgent',
    subject: 'BGP Routing latency surge in Blue Area office',
    unreadCountCustomer: 0,
    unreadCountStaff: 0,
    createdAt: '2026-08-24T14:00:00Z',
    updatedAt: '2026-08-24T15:30:00Z',
    lastMessageAt: '2026-08-24T15:30:00Z',
    customer: {
      id: 'cus_zahid_blue',
      companyId: 'cmp_prime_networks_01',
      customerCode: 'CUS-BLUE-8820',
      fullName: 'Zahid Bilal (TechCorp PK)',
      phone: '+92 333 1122334',
      username: 'techcorp_blue',
      address: 'Tower B, 4th Floor, Blue Area',
      area: 'Blue Area Corporate Core',
      city: 'Islamabad',
      customerClass: 'corporate',
      packageName: '250 Mbps Enterprise Dedicated',
      packageSpeed: '250 Mbps',
      monthlyBilling: 9500,
      pppoeStatus: 'online',
      onuSignalDbm: -17.9,
      oltPonPort: 'Huawei-MA5608T // PON-1',
      status: 'active',
      languagePreference: 'en',
      createdAt: '2025-11-01T00:00:00Z',
      updatedAt: '2026-08-25T00:00:00Z',
    },
    lastMessage: {
      id: 'msg_08',
      conversationId: 'conv_zahid_blue_03',
      companyId: 'cmp_prime_networks_01',
      senderType: 'staff',
      senderName: 'NOC Lead (Moiz)',
      messageType: 'system',
      content: 'Chat closed with outcome: Issue Resolved. BGP routes cleared.',
      status: 'read',
      isInternalNote: false,
      isPublicNote: false,
      isDeleted: false,
      createdAt: '2026-08-24T15:30:00Z',
    },
  },
];

export const mockDeskMessages: Message[] = [
  {
    id: 'msg_01',
    conversationId: 'conv_ali_f10_01',
    companyId: 'cmp_prime_networks_01',
    senderCustomerId: 'cus_ali_f10',
    senderType: 'customer',
    senderName: 'Ali Hassan',
    messageType: 'text',
    content: 'Hello, the red light is blinking on my fiber router for the last 15 minutes. The internet connection is disconnected.',
    status: 'read',
    isInternalNote: false,
    isPublicNote: false,
    isDeleted: false,
    createdAt: '2026-08-25T10:40:12Z',
  },
  {
    id: 'msg_02',
    conversationId: 'conv_ali_f10_01',
    companyId: 'cmp_prime_networks_01',
    senderUserId: 'usr_ayesha_hd',
    senderType: 'staff',
    senderName: 'Ayesha Khan (Helpdesk)',
    messageType: 'text',
    content: 'Hello Ali. Let me inspect your optical signal link in our SmartOLT telemetry right now.',
    status: 'read',
    isInternalNote: false,
    isPublicNote: false,
    isDeleted: false,
    createdAt: '2026-08-25T10:41:05Z',
  },
  {
    id: 'msg_03_note',
    conversationId: 'conv_ali_f10_01',
    companyId: 'cmp_prime_networks_01',
    senderUserId: 'usr_ayesha_hd',
    senderType: 'staff',
    senderName: 'Ayesha Khan (Helpdesk)',
    messageType: 'text',
    content: 'SmartOLT shows severe attenuation at -32.54 dBm on EPON0/2:4. Checking joint box on Street 18.',
    status: 'read',
    isInternalNote: true,
    isPublicNote: false,
    isDeleted: false,
    createdAt: '2026-08-25T10:41:40Z',
  },
  {
    id: 'msg_04',
    conversationId: 'conv_ali_f10_01',
    companyId: 'cmp_prime_networks_01',
    senderUserId: 'usr_ayesha_hd',
    senderType: 'staff',
    senderName: 'Ayesha Khan (Helpdesk)',
    messageType: 'text',
    content: 'Our telemetry detected an optical attenuation drop. I have escalated this to Van 04 for urgent on-site OTDR splicing.',
    status: 'delivered',
    isInternalNote: false,
    isPublicNote: false,
    isDeleted: false,
    createdAt: '2026-08-25T10:42:00Z',
  },
];

export const mockCustomer360Data: Customer360 = {
  customer: mockDeskConversations[0].customer!,
  opticalTelemetry: {
    rxDbm: -19.24,
    txDbm: 2.15,
    status: 'nominal',
    oltName: 'Huawei-MA5608T-F10',
    ponPort: 'EPON0/2:4',
    onuSerial: 'HWTC-98B2-F104',
    onuModel: 'EchoLife HG8245H',
    lastPolledAt: '2026-08-25T10:43:00Z',
  },
  billing: {
    packageName: '50 Mbps Ultra Fiber',
    speed: '50 Mbps / 50 Mbps',
    monthlyDues: 3500,
    balanceDue: 0,
    billingCycle: 'Monthly (1st to 1st)',
    paymentStatus: 'paid',
    expiryDate: '2026-09-15',
    lastPaymentDate: '2026-08-01',
  },
  networkSession: {
    pppoeUsername: 'ali_f10',
    ipAddress: '192.168.10.45',
    macAddress: 'F8:4D:89:A2:3B:11',
    sessionUptime: '14 days 6 hours',
    downloadSpeed: '48.8 Mbps',
    uploadSpeed: '49.2 Mbps',
    nasIp: '103.255.4.1',
  },
  recentTickets: [
    {
      id: 'tkt_01',
      ticketNumber: 'TKT-F10-902',
      category: 'Fiber Break / Splicing',
      status: 'resolved',
      priority: 'normal',
      createdAt: '2026-07-12T09:00:00Z',
      resolvedAt: '2026-07-12T11:30:00Z',
    },
  ],
  recentConversations: [
    {
      id: 'conv_prev_01',
      subject: 'Inquiry regarding 100 Mbps speed upgrade',
      status: 'closed',
      lastMessageAt: '2026-08-10T14:20:00Z',
      closedAt: '2026-08-10T14:45:00Z',
    },
  ],
};
